### ISSUE TITLE
Wrong data is returning after sending correct token and scan

### ISSUE THREAD

**Issue by ADESTAR** [nptracker/NPS-SADL#1]
I am receiving wrong results when i use the API
api.nptracker.co.za/NPS-DL/?token={my real token}&device=defaultValue&scan={real scan info}

I create scan code according to the sample app given on git. If i user this scan code and token on link given in in sample app, result is OK

Sample link is 

http://lic.nptracker.co.za/DriversLicence.html?token={my real token}&device=defaultValue&scan={my real scan}&type=Drivers%20Licence&scantype=null&count=56&version=0203

But i am receiving the wrong dummy responses 

{
    "results": {
        "EncryptionVersion": "UNSUPORTED",
        "BarcodeVersion": "UNKNOWN",
        "Initial": "DECRYPTION",
        "Surname": "ERROR",
        "IDNo": "9999999999999",
        "LicNo": "---",
        "IssuedBy": "UNKNOWN",
        "Issued": "---",
        "ValidFrom": "---",
        "ValidTo": "01-01-1970",
        "Code": "---",
        "unlock": "true",
        "checks": {
            "VehRestr": "---",
            "UserRestr": "---",
            "expire": "---",
            "age": "---",
            "gender": "---"
        }
    }
}

**Comment by nptracker** [comment]
Can you please email us at info@nptracker.co.za {my real scan} hex-encoded barcode for us to fault find the issue.
